/*
 * Copyright (c) 2019, Arm Limited and affiliates.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef WISUN_TEST_CERTIFICATES_H_
#define WISUN_TEST_CERTIFICATES_H_

const uint8_t WISUN_ROOT_CERTIFICATE[] = {
#if 0
/* Global Sign Root CA */
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIICIDCCAcagAwIBAgIBATAKBggqhkjOPQQDAjB1MQswCQYDVQQGEwJCRTEZMBcG\r\n"
    "A1UEChMQR2xvYmFsU2lnbiBudi1zYTEaMBgGA1UECxMRRm9yIFRlc3QgVXNlIE9u\r\n"
    "bHkxLzAtBgNVBAMTJkdsb2JhbFNpZ24gV2ktU1VOIEZBTiBFQ0MgVGVzdCBSb290\r\n"
    "IENBMCAXDTE4MDcxODAwMDAwMFoYDzk5OTkxMjMxMjM1OTU5WjB1MQswCQYDVQQG\r\n"
    "EwJCRTEZMBcGA1UEChMQR2xvYmFsU2lnbiBudi1zYTEaMBgGA1UECxMRRm9yIFRl\r\n"
    "c3QgVXNlIE9ubHkxLzAtBgNVBAMTJkdsb2JhbFNpZ24gV2ktU1VOIEZBTiBFQ0Mg\r\n"
    "VGVzdCBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEp5HbQNUb1bW4\r\n"
    "LnUfs77YXysSp+fXXomez+pnzXIb4FJP94knwauyoMd99BsmW/fK/yHzk6Rs4Fma\r\n"
    "T5m7eRpll6NFMEMwDgYDVR0PAQH/BAQDAgIEMBIGA1UdEwEB/wQIMAYBAf8CAQIw\r\n"
    "HQYDVR0OBBYEFD0qd4ApGSsRSUwEnFv9fIyYnH+SMAoGCCqGSM49BAMCA0gAMEUC\r\n"
    "IQDjD8vQ8PbGY+MCP5e4PW0O0ValmtnVg4DXoGYRz+tioQIgGpHT7NmOHtEg4HRG\r\n"
    "BJe60OcyxFjpDsp/R2pGArN9iuE=\r\n"
    "-----END CERTIFICATE-----"
#else
/* Wi-SUN test root CA */
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIBojCCAUmgAwIBAgIFAPf29t8wCgYIKoZIzj0EAwIwMTEOMAwGA1UECgwFV2lT\r\n"
    "VU4xEzARBgNVBAMMCldpU1VOIFJvb3QxCjAIBgNVBAUTATEwIBcNMTcwNzA0MjEw\r\n"
    "NDAyWhgPOTk5OTEyMzEyMzU5NTlaMDExDjAMBgNVBAoMBVdpU1VOMRMwEQYDVQQD\r\n"
    "DApXaVNVTiBSb290MQowCAYDVQQFEwExMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD\r\n"
    "QgAEVrJidrjt1nWFVA/VOA/1XKARMBv9t+9XbnErRKJhwudMEUguImA6Ns5TS6o6\r\n"
    "wDDGjYF6JzO1htL1+MTNFkId+KNMMEowDwYDVR0TAQH/BAUwAwEB/zARBgNVHQ4E\r\n"
    "CgQIQP089aoIBgswDgYDVR0PAQH/BAQDAgEGMBQGA1UdIAEB/wQKMAgwBgYEVR0g\r\n"
    "ADAKBggqhkjOPQQDAgNHADBEAiBYqSiYL0Tu8D/zzU8TajVkzKMw6qkku+UIezPn\r\n"
    "2Tv6rAIgP5+YwqTLC9QTfuz2/XN6Ta5Hd4zgyLSvc1BXm94r06k=\r\n"
    "-----END CERTIFICATE-----"
#endif
};

const uint8_t WISUN_MCA_CERTIFICATE[] = {
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIByzCCAXCgAwIBAgIFAInnL70wCgYIKoZIzj0EAwIwMTEOMAwGA1UECgwFV2lT\r\n"
    "VU4xEzARBgNVBAMMCldpU1VOIFJvb3QxCjAIBgNVBAUTATEwIBcNMjEwNTI5MjAx\r\n"
    "OTI0WhgPOTk5OTEyMzEyMzU5NTlaMDoxCzAJBgNVBAYTAlVTMQswCQYDVQQKDAJU\r\n"
    "STESMBAGA1UEAwwJV2lTVU4gTUNBMQowCAYDVQQFEwEyMFkwEwYHKoZIzj0CAQYI\r\n"
    "KoZIzj0DAQcDQgAEff6D5/8TiDCHY/C66gZTnQ8eQiDpSrZqheOm8LeRUT9wtD7f\r\n"
    "tk8cS9iHURvNJzokoiyAaMQNHg1G4IkXpq/PTqNqMGgwEgYDVR0TAQH/BAgwBgEB\r\n"
    "/wIBATARBgNVHQ4ECgQIT3tWlvumf2cwEwYDVR0jBAwwCoAIQP089aoIBgswDgYD\r\n"
    "VR0PAQH/BAQDAgIEMBoGA1UdIAEB/wQQMA4wDAYKKwYBBAGC5CUBATAKBggqhkjO\r\n"
    "PQQDAgNJADBGAiEAkb/mSulx8xW7cbl1b7CkrxiOFq6n7xy3o4sxaj2APeoCIQCs\r\n"
    "EkFFa5ROJP0iIRsWII/x45Rb1rbUX+lta8uCNz14JQ==\r\n"
    "-----END CERTIFICATE-----"
};

const uint8_t WISUN_MICA_CERTIFICATE[] = {
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIB1DCCAXqgAwIBAgIFAL6ICq4wCgYIKoZIzj0EAwIwOjELMAkGA1UEBhMCVVMx\r\n"
    "CzAJBgNVBAoMAlRJMRIwEAYDVQQDDAlXaVNVTiBNQ0ExCjAIBgNVBAUTATIwIBcN\r\n"
    "MjEwNTI5MjAyMDUwWhgPOTk5OTEyMzEyMzU5NTlaMDsxCzAJBgNVBAYTAlVTMQsw\r\n"
    "CQYDVQQKDAJUSTETMBEGA1UEAwwKV2lTVU4gTUlDQTEKMAgGA1UEBRMBMzBZMBMG\r\n"
    "ByqGSM49AgEGCCqGSM49AwEHA0IABIoDqK7Dh2aNPS1KgR3dL0lwVR8JEddemMrx\r\n"
    "S5J3ok7qyrYcSrfW4xwm+xpOfcTiUredc+UyAkG+HJlyZ0BQVbijajBoMBIGA1Ud\r\n"
    "EwEB/wQIMAYBAf8CAQAwEQYDVR0OBAoECEHbJKKDpOHaMBMGA1UdIwQMMAqACE97\r\n"
    "Vpb7pn9nMA4GA1UdDwEB/wQEAwICBDAaBgNVHSABAf8EEDAOMAwGCisGAQQBguQl\r\n"
    "AQEwCgYIKoZIzj0EAwIDSAAwRQIgPNu16+1bz+sicscEi0cckXgmTp8MdrN7cJiG\r\n"
    "jpn/wd8CIQCujzg6ami/lXsLQULWKD1fDEZZYrGNL9Q583/MdnYN1Q==\r\n"
    "-----END CERTIFICATE-----"
};

const uint8_t WISUN_CLIENT_CERTIFICATE_FROM_MICA[] = {
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIBpDCCAUqgAwIBAgIFAKMNuFswCgYIKoZIzj0EAwIwOzELMAkGA1UEBhMCVVMx\r\n"
    "CzAJBgNVBAoMAlRJMRMwEQYDVQQDDApXaVNVTiBNSUNBMQowCAYDVQQFEwEzMCAX\r\n"
    "DTIxMDUyOTIwMjEzM1oYDzk5OTkxMjMxMjM1OTU5WjAAMFkwEwYHKoZIzj0CAQYI\r\n"
    "KoZIzj0DAQcDQgAElomHreAky/YrhmmV7609tJcElvGz06oVyIvr3Fr8qnW8bG8t\r\n"
    "1DYERozKAbqkz2j/7avxluJLpfc+Hj1U9bXj3KN0MHIwEwYDVR0jBAwwCoAIQdsk\r\n"
    "ooOk4dowDgYDVR0PAQH/BAQDAgOIMCgGA1UdEQEB/wQeMBygGgYIKwYBBQUHCASg\r\n"
    "DjAMBgUrBgEEAQQDq8EjMCEGA1UdJQEB/wQXMBUGCSsGAQQBguQlAQYIKwYBBQUH\r\n"
    "AwIwCgYIKoZIzj0EAwIDSAAwRQIhAPmENkMqPJxLURPTkyxlSvoskKSHyak45X8i\r\n"
    "EKXVv7BJAiAMq54B1KhVCzi2KIwqWpbdMrCFGUQj93rKpeGzzaedVA==\r\n"
    "-----END CERTIFICATE-----"
};

const uint8_t WISUN_CLIENT_CERTIFICATE_FROM_MICA_KEY[] = {
    "-----BEGIN PRIVATE KEY-----\r\n"
    "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgXULl7wRN5pt39ZQE\r\n"
    "lTaj511QCUagH5iLhirG4qTr93ahRANCAASWiYet4CTL9iuGaZXvrT20lwSW8bPT\r\n"
    "qhXIi+vcWvyqdbxsby3UNgRGjMoBuqTPaP/tq/GW4kul9z4ePVT1tePc\r\n"
    "-----END PRIVATE KEY-----"
};

const uint8_t WISUN_CLIENT_CERTIFICATE[] = {
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIBmTCCAUCgAwIBAgIFAO3CI8YwCgYIKoZIzj0EAwIwMTEOMAwGA1UECgwFV2lT\r\n"
    "VU4xEzARBgNVBAMMCldpU1VOIFJvb3QxCjAIBgNVBAUTATEwIBcNMjEwNTI5MDQx\r\n"
    "NDAwWhgPOTk5OTEyMzEyMzU5NTlaMAAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC\r\n"
    "AASn32VuKHiaszuKDBgo5TeQXuh6yWXZ6mQDYJk7GQeorVBI6x1olS0UKLg7ICMZ\r\n"
    "woZhiMiod58RYEPEXZU6g8D8o3QwcjATBgNVHSMEDDAKgAhA/Tz1qggGCzAOBgNV\r\n"
    "HQ8BAf8EBAMCA4gwKAYDVR0RAQH/BB4wHKAaBggrBgEFBQcIBKAOMAwGBSsGAQQB\r\n"
    "BAOrwSMwIQYDVR0lAQH/BBcwFQYJKwYBBAGC5CUBBggrBgEFBQcDAjAKBggqhkjO\r\n"
    "PQQDAgNHADBEAiA++iYNejxsZW+sFEG8+SzPlUoYc53tBFiPPBgAerBV2QIgPvOG\r\n"
    "EqhbKhdp7fX7afNnvTd4Ba10PEWQEcsMhmVT+XQ=\r\n"
    "-----END CERTIFICATE-----"
};

const uint8_t WISUN_CLIENT_GS_CERTIFICATE[] = {
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIICMDCCAdagAwIBAgIQASMTIpy6Qc1PEaj7BWgI+zAKBggqhkjOPQQDAjCBgzEL\r\n"
    "MAkGA1UEBhMCQkUxGTAXBgNVBAoTEEdsb2JhbFNpZ24gbnYtc2ExGjAYBgNVBAsT\r\n"
    "EUZvciBUZXN0IFVzZSBPbmx5MT0wOwYDVQQDEzRHbG9iYWxTaWduIFdpLVNVTiBG\r\n"
    "QU4gRUNDIFRlc3QgU3ViLU1hbnVmYWN0dXJlciBDQSAxMB4XDTIyMTIxNTE2Mzkx\r\n"
    "NloXDTIzMDMxNTE2MzkxNlowADBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABC80\r\n"
    "USJEt/otMLraxEPhe+tCYilJBFaKAEjmaViPC1fZh4wMsQJW5zDNL91YLoU20h8v\r\n"
    "juTioITabdUrsatDmOCjga0wgaowKgYDVR0RAQH/BCAwHqAcBggrBgEFBQcIBKAQ\r\n"
    "MA4GAykBAQQHMTIzNDU2NzAOBgNVHQ8BAf8EBAMCB4AwHgYDVR0lBBcwFQYJKwYB\r\n"
    "BAGC5CUBBggrBgEFBQcDAjAdBgNVHQ4EFgQUxzbKKF8Sg6DH/AL0Lty8VnrPfxAw\r\n"
    "DAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBQ3ttkOUJkFBUV3L09XhhFkvRu9vDAK\r\n"
    "BggqhkjOPQQDAgNIADBFAiEA18M/fCmdtD9Vvfb4B8ryXhgbS1iNHOjQCMRD7Ox/\r\n"
    "9kICIDVV3KXMHnlkUCjRiIaZGTX0qeTjFbadYnSh8Ad99xKR\r\n"
    "-----END CERTIFICATE-----"
};

const uint8_t WISUN_CLIENT_KEY[] = {
    "-----BEGIN PRIVATE KEY-----\r\n"
    "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgxFocOSC2agqrJGYC\r\n"
    "R8Q0VfTaNBQSsQXxvMgr3byWtvyhRANCAASn32VuKHiaszuKDBgo5TeQXuh6yWXZ\r\n"
    "6mQDYJk7GQeorVBI6x1olS0UKLg7ICMZwoZhiMiod58RYEPEXZU6g8D8\r\n"
    "-----END PRIVATE KEY-----"
};

const uint8_t WISUN_CLIENT_GS_KEY[] = {
    "-----BEGIN EC PRIVATE KEY-----\r\n"
    "MHcCAQEEIKntZLN+RQbjNtxiwwvNKr0ZRL5tbj+4rYvSlkfTMauKoAoGCCqGSM49\r\n"
    "AwEHoUQDQgAELzRRIkS3+i0wutrEQ+F760JiKUkEVooASOZpWI8LV9mHjAyxAlbn\r\n"
    "MM0v3VguhTbSHy+O5OKghNpt1Suxq0OY4A==\r\n"
    "-----END EC PRIVATE KEY-----"
};

#endif /* WISUN_TEST_CERTIFICATES_H_ */
