---------------------------------------------------------------------------------------------------
-- CoAP CSMP Wireshark dissector
--
-- Wireshark Lua dissector : coap_csmp_dissector.lua
-- ProtoBuf definition file: csmp.proto
--
-- Enables Wireshark to dissect CSMP packet payloads into TLVs and fields based on the
-- TLV Protobuf definitions in csmp.proto file
-- This is a CSMP Lua dissector is built on Wireshark's ProtoBuf dissector
-- Refer Readme for install and usage instructions
--
-- Author: Manojna CSL (mcsl@cisco.com, manojnacsl@gmail.com)
---------------------------------------------------------------------------------------------------

-- Load required fields, ports
local CSMP_PORT_RFC = '61628'
local CSMP_PORT_CLC = '61624'
fUdpDstPort = Field.new("udp.dstport")
fUdpSrcPort = Field.new("udp.srcport")

-- Create the CSMP Proto, add TLV fields
local oProtoCsmp = Proto('csmp', 'CSMP')
local pfTlvId     = ProtoField.uint32('csmp.tlvid',  'ID',     base.DEC)
local pfTlvLength = ProtoField.uint32('csmp.tlvlen', 'Length', base.DEC)
local pfTlvData   = ProtoField.bytes('csmp.tlvdata', 'Raw Data')
oProtoCsmp.fields = {pfTlvId, pfTlvLength, pfTlvData}

-- Lookup table for TLV names
local tTlvIdStr = {
      [1] = 'TLV Index',
      [2] = 'Device ID',
      [6] = 'NMS Redirect Request',
      [7] = 'Session ID',
      [8] = 'Description Request',
     [10] = 'Hardware Settings',
     [11] = 'Hardware Description',
     [12] = 'Interface Description',
     [13] = 'Report Subscribe',
     [16] = 'IP Address',
     [17] = 'IP Route',
     [18] = 'Current Time',
     [19] = 'Interface Settings',
     [20] = 'WPAN Settings',
     [21] = 'RPL Settings',
     [22] = 'Uptime',
     [23] = 'Interface Metrics',
     [24] = 'Interface Detail Metrics',
     [25] = 'IP Route RPL Metrics',
     [28] = 'Echo Request',
     [29] = 'Echo Response',
     [30] = 'Ping Request',
     [31] = 'Ping Response',
     [32] = 'Reboot Request',
     [33] = 'IEEE-802.1x Status',
     [34] = 'IEEE-802.11i Status',
     [35] = 'WPAN Status',
     [36] = 'DHCPv6 Client Status',
     [37] = 'Radio Link Stats',
     [38] = 'IEEE-802.15.4 DevLink Stats',
     [39] = 'IEEE-802.15.4 Link Stats',
     [40] = 'WPAN Link Stats',
     [41] = 'PPP Link Stats',
     [42] = 'CGMS Settings',
     [43] = 'CGMS Status',
     [44] = 'CGMS Notification',
     [45] = 'CGMS Stats',
     [46] = 'PPP Settings',
     [47] = 'IEEE-802,1x Settings',
     [48] = 'IEEE-802.15.4 Beacon Stats',
     [49] = 'Silence Request',
     [50] = 'UDP Metric',
     [51] = 'IEEE-P19012 Stats',
     [52] = 'IEEE-802.15.4 Neighbors',
     [53] = 'RPL Instance',
     [54] = 'RPL Parent',
     [55] = 'Group Assign',
     [56] = 'Group Evict',
     [57] = 'Group Match',
     [58] = 'Group Info',
     [61] = 'LoWPAN PHY Stats',
     [62] = 'LoWPAN MAC Status',
     [63] = 'LoWPAN PHY Settings',
     [65] = 'Transfer Request',
     [67] = 'ImageBlock',
     [68] = 'Load Request',
     [69] = 'Cancel Load Request',
     [70] = 'Set Backup Request',
     [71] = 'Transfer Response',
     [72] = 'Load Response',
     [73] = 'Cancel Load Response',
     [74] = 'Set Backup Response',
     [75] = 'Firmware Image Info',
     [76] = 'Signature Validity',
     [77] = 'Signature',
     [78] = 'Signature Certificate',
     [79] = 'Signature Settings',
     [80] = 'IEEE-802.1x AAA Security',
     [81] = 'IEEE-802.1x Client Security',
     [84] = 'Network Neighbours',
     [86] = 'System Reset Stats',
     [88] = 'DiffServ Metrics',
     [91] = 'Outage Recovery',
     [92] = 'Start DM Session',
     [93] = 'End DM Session',
     [95] = 'IEEE-P19012 Neighbour',
     [96] = 'SerialDev Settings',
     [97] = 'SerialDev Metrics',
     [98] = 'IPM Address Settings',
    [107] = 'Leds Settings',
    [108] = 'Leds Status',
    [111] = 'MAPT Status',
    [112] = 'MAPT Metrics',
    [115] = 'RawSocket Forwarder Settings',
    [116] = 'RawSocket Forwarder Status',
    [117] = 'RawSocket Forwarder Metrics',
    [120] = 'NAT44 Static Map',
    [121] = 'NAT44 DynamicMap',
    [122] = 'NAT44 Interface',
    [124] = 'NetStat',
    [125] = 'ARP Cache',
    [130] = 'IEEE-P19012 RPL Metrics',
    [139] = 'Console Settings',
    [140] = 'Zeroise Node',
    [141] = 'Network Role',
    [142] = 'IOx Settings',
    [143] = 'IOx Management',
    [144] = 'IOx Credentials',
    [145] = 'IOx Host Exec',
    [146] = 'IOx Host Status',
    [147] = 'IOx Status',
    [148] = 'Downward Route Query',
    [149] = 'Downward Route Number',
    [150] = 'App Header Info',
    [155] = 'LoWPAN Adaptive PHY Status Query',
    [156] = 'Adaptive Modulation Settings',
    [157] = 'Adaptive Modulation Status',
    [163] = 'Channel Control',
    [170] = 'DTLS Relay Settings',
    [171] = 'Certificate Re-Enroll Settings',
    [172] = 'Certificate Bundle',
    [173] = 'Certificate Auto-Renew Settings',
    [180] = 'Patch Capability Info',
    [200] = 'BBU Status',
    [201] = 'BBU Settings',
    [202] = 'BBU Diagnostic Info',
    [214] = 'Heater Settings',
    [215] = 'Heater Status',
    [217] = 'External Alarm Setting',
    [218] = 'External Alarm Status',
    [219] = 'StoredInfo',
    [220] = 'FastSync Status',
    [240] = 'MPL Settings',
    [241] = 'MPL Stats',
    [242] = 'MPL Reset',
    [243] = 'MPL Domain Address',
    [301] = 'SwitchPort Settings',
    [302] = 'SwitchPort Metrics',
    [303] = 'SwitchPort Detail Metrics',
    [307] = 'ACL Deny Event Message',
    [308] = 'MacSec Settings',
    [309] = 'MacSec Status',
    [310] = 'Logging Capability',
    [311] = 'Logging Status',
    [312] = 'Logging Report',
    [313] = 'RPL Stats',
    [314] = 'DHCPv6 Stats',
    [315] = 'IEEE-802.15.4g Neighbor Settings',
    [316] = 'IEEE-P19012 Neighbor Settings',
    [320] = 'FMR Operate Try',
    [321] = 'FMR Operate Catch',
    [325] = 'Scan Channel RSSI Settings',
    [326] = 'Channel RSSI Stats',
    [327] = 'Channel RSSI',
    [328] = 'Link Test Settings',
    [329] = 'Link Test Stats',
    [330] = 'Channel Packet Stats Clear',
    [331] = 'Channel Packet Stats',
    [332] = 'Radio Neighbor Stats Clear',
    [333] = 'Radio Neighbor Stats',
    [334] = 'Channel Function Settings',
    [335] = 'EDFE Mode Settings',
    [336] = 'LoWPAN MTU Settings',
    [337] = 'Dwell Interval Settings',
    [340] = 'StackMode Settings',
    [341] = 'Wireless Console Setting',
    [342] = 'Wireless Console Authorise',
    [343] = 'StackMode Time',
    [344] = 'StackMode Response',
    [350] = 'Power Outage Notification (PON)',
    [351] = 'Power Restoration Notification (PRN)',
    [352] = 'Backup Power Setting',
    [353] = 'Outage Stats',
    [360] = 'P2P Instance Info',
    [361] = 'P2P Route Info',
    [362] = 'P2P Stats',
    [363] = 'P2P Delete Route',
    [364] = 'P2P Start Discover',
    [500] = 'Event Report',
    [501] = 'Event Index',
    [502] = 'Event Subscribe',
    [510] = 'Event Stats',
    [525] = 'Debug Current Node Status',
    [540] = 'ETX Algorithm Settings',
    [550] = 'Sniffer Settings',
    [551] = 'Sniffer Framecount',
    [600] = 'FFN Gateway Settings',
    [601] = 'FFN Child Stats',
    }

-- Add Protobuf message dissector
-- Note: TLV message names in protobufMessageMap must match (case-sensitive) as in
-- csmp.proto file and have the package name (csmp) as their common prefix
local oProtoProtobuf = Dissector.get("protobuf")
local protobufMessageMap = {
      [1] = "csmp.TlvIndex",
      [2] = "csmp.DeviceID",
      [6] = "csmp.NMSRedirectRequest",
      [7] = "csmp.SessionID",
      [8] = "csmp.DescriptionRequest",
     [10] = "csmp.HardwareSettings",
     [11] = "csmp.HardwareDesc",
     [12] = "csmp.InterfaceDesc",
     [13] = "csmp.ReportSubscribe",
     [16] = "csmp.IPAddress",
     [17] = "csmp.IPRoute",
     [18] = "csmp.CurrentTime",
     [19] = "csmp.InterfaceSettings",
     [20] = "csmp.WPANSettings",
     [21] = "csmp.RPLSettings",
     [22] = "csmp.Uptime",
     [23] = "csmp.InterfaceMetrics",
     [24] = "csmp.InterfaceDetailMetrics",
     [25] = "csmp.IPRouteRPLMetrics",
     [28] = "csmp.EchoRequest",
     [29] = "csmp.EchoResponse",
     [30] = "csmp.PingRequest",
     [31] = "csmp.PingResponse",
     [32] = "csmp.RebootRequest",
     [33] = "csmp.Ieee8021xStatus",
     [34] = "csmp.Ieee80211iStatus",
     [35] = "csmp.WPANStatus",
     [36] = "csmp.DHCP6ClientStatus",
     [37] = "csmp.RadioLinkStats",
     [38] = "csmp.Ieee802154DevLinkStats",
     [39] = "csmp.Ieee802154LinkStats",
     [40] = "csmp.WPANLinkStats",
     [41] = "csmp.PPPLinkStats",
     [42] = "csmp.CGMSSettings",
     [43] = "csmp.CGMSStatus",
     [44] = "csmp.CGMSNotification",
     [45] = "csmp.CGMSStats",
     [46] = "csmp.PPPSettings",
     [47] = "csmp.Ieee8021xSettings",
     [48] = "csmp.Ieee802154BeaconStats",
     [49] = "csmp.SilenceRequest",
     [50] = "csmp.UDPMetrics",
     [51] = "csmp.IeeeP19012Stats",
     [52] = "csmp.Neighbor802154G",
     [53] = "csmp.RplInstance",
     [54] = "csmp.RPLParent",
     [55] = "csmp.GroupAssign",
     [56] = "csmp.GroupEvict",
     [57] = "csmp.GroupMatch",
     [58] = "csmp.GroupInfo",
     [61] = "csmp.LowpanPhyStats",
     [62] = "csmp.LowpanMacStats",
     [63] = "csmp.LowpanPhySettings",
     [65] = "csmp.TransferRequest",
     [67] = "csmp.ImageBlock",
     [68] = "csmp.LoadRequest",
     [69] = "csmp.CancelLoadRequest",
     [70] = "csmp.SetBackupRequest",
     [71] = "csmp.TransferResponse",
     [72] = "csmp.LoadResponse",
     [73] = "csmp.CancelLoadResponse",
     [74] = "csmp.SetBackupResponse",
     [75] = "csmp.FirmwareImageInfo",
     [76] = "csmp.SignatureValidity",
     [77] = "csmp.Signature",
     [78] = "csmp.SignatureCert",
     [79] = "csmp.SignatureSettings",
     [80] = "csmp.Ieee8021xAAASec",
     [81] = "csmp.Ieee8021xClientSec",
     [84] = "csmp.NetworkNeighbors",
     [86] = "csmp.SysResetStats",
     [88] = "csmp.DiffServMetrics",
     [91] = "csmp.OutageRecovery",
     [92] = "csmp.StartDMSession",
     [93] = "csmp.EndDMSession",
     [95] = "csmp.NeighborP19012",
     [96] = "csmp.SerialDevSettings",
     [97] = "csmp.SerialDevMetrics",
     [98] = "csmp.IPMAddressSettings",
    [107] = "csmp.LedsSettings",
    [108] = "csmp.LedsStatus",
    [111] = "csmp.MAPTStatus",
    [112] = "csmp.MAPTMetrics",
    [115] = "csmp.RawSockForwarderSettings",
    [116] = "csmp.RawSockForwarderStatus",
    [117] = "csmp.RawSockForwarderMetrics",
    [120] = "csmp.NAT44StaticMap",
    [121] = "csmp.NAT44DynamicMap",
    [122] = "csmp.NAT44Interface",
    [124] = "csmp.NetStat",
    [125] = "csmp.ArpCache",
    [130] = "csmp.IeeeP19012RPLMetrics",
    [139] = "csmp.ConsoleSettings",
    [140] = "csmp.ZeroizeNode",
    [141] = "csmp.NetworkRole",
    [142] = "csmp.IOxSettings",
    [143] = "csmp.IOxManagement",
    [144] = "csmp.IOxCredentials",
    [145] = "csmp.IOxHostExec",
    [146] = "csmp.IOxHostStatus",
    [147] = "csmp.IOxStatus",
    [148] = "csmp.DwardRouteQuery",
    [149] = "csmp.DwardRouteNumber",
    [150] = "csmp.AppHeaderInfo",
    [155] = "csmp.LowpanAdaptivePhyStatusQuery",
    [156] = "csmp.AdaptiveModulationSettings",
    [157] = "csmp.AdaptiveModulationStatus",
    [163] = "csmp.ChannelControl",
    [170] = "csmp.DtlsRelaySettings",
    [171] = "csmp.CertReEnrollSettings",
    [172] = "csmp.CertBundle",
    [173] = "csmp.CertAutoRenewSettings",
    [180] = "csmp.PatchCapabilityInfo",
    [200] = "csmp.BBUStatus",
    [201] = "csmp.BBUSettings",
    [202] = "csmp.BBUDiagInfo",
    [214] = "csmp.HeaterSettings",
    [215] = "csmp.HeaterStatus",
    [217] = "csmp.ExtAlarmSetting",
    [218] = "csmp.ExtAlarmStatus",
    [219] = "csmp.StoredInfo",
    [220] = "csmp.FastSyncStatus",
    [240] = "csmp.MplSettings",
    [241] = "csmp.MplStats",
    [242] = "csmp.MplReset",
    [243] = "csmp.MplDomainAddress",
    [301] = "csmp.SwitchPortSettings",
    [302] = "csmp.SwitchPortMetrics",
    [303] = "csmp.SwitchPortDetailMetrics",
    [307] = "csmp.AclDenyEventMsg",
    [308] = "csmp.MACSecSettings",
    [309] = "csmp.MACsecStatus",
    [310] = "csmp.LoggingCapability",
    [311] = "csmp.LoggingStatus",
    [312] = "csmp.LoggingReport",
    [313] = "csmp.RPLStats",
    [314] = "csmp.DHCP6Stats",
    [315] = "csmp.Neighbor802154GSettings",
    [316] = "csmp.NeighborP19012Settings",
    [320] = "csmp.FMROperateTry",
    [321] = "csmp.FMROperateCatch",
    [325] = "csmp.ScanChannelRssiSettings",
    [326] = "csmp.ChannelRssiStats",
    [327] = "csmp.ChannelRssi",
    [328] = "csmp.LinkTestSettings",
    [329] = "csmp.LinkTestStats",
    [330] = "csmp.ChannelPacketStatsClr",
    [331] = "csmp.ChannelPacketStats",
    [332] = "csmp.RadioNeighborStatsClr",
    [333] = "csmp.RadioNeighborStats",
    [334] = "csmp.ChannelFunctionSettings",
    [335] = "csmp.EDFEmodeSettings",
    [336] = "csmp.LowpanMtuSettings",
    [337] = "csmp.DwellIntervalSettings",
    [340] = "csmp.StackModeSettings",
    [341] = "csmp.WirelessConsoleSetting",
    [342] = "csmp.WirelessConsoleAuthorize",
    [343] = "csmp.StackModeTime",
    [344] = "csmp.StackModeResponse",
    [350] = "csmp.PON",
    [351] = "csmp.PRN",
    [352] = "csmp.BackupPowerSetting",
    [353] = "csmp.OutageStats",
    [360] = "csmp.P2pInstanceInfo",
    [361] = "csmp.P2pRouteInfo",
    [362] = "csmp.P2pStats",
    [363] = "csmp.P2pDeleteRoute",
    [364] = "csmp.P2pStartDiscover",
    [500] = "csmp.EventReport",
    [501] = "csmp.EventIndex",
    [502] = "csmp.EventSubscribe",
    [510] = "csmp.EventStats",
    [525] = "csmp.DbgCurrentNodeStatus",
    [540] = "csmp.ETXAlgorithmSettings",
    [550] = "csmp.SnifferSettings",
    [551] = "csmp.SnifferFramecount",
    [600] = "csmp.FFNGatewaySettings",
    [601] = "csmp.FFNChildStats",
    }

-- VarInt parser
local function getVarInt(buf)
   local i = 0
   local value = 0
   while( buf(i,1):uint() > 128 ) do
      value = value + ((buf(i, 1):uint()-128) << (7*i))
      i = i + 1
   end
   value = value + (buf(i, 1):uint() << (7*i))
   i = i + 1
   return i, value
end

function oProtoCsmp.dissector(oTvbData, oPinfo, oTreeItemRoot)
   
   -- Do not parse this CoAP payload if not on CSMP port
   if tostring(fUdpDstPort()) ~= CSMP_PORT_RFC and tostring(fUdpSrcPort()) ~= CSMP_PORT_RFC then return end

   --oPinfo.cols.protocol = 'CSMP' -- Comment out and leave column protocol as CoAP/PB
   local oSubtree = oTreeItemRoot:add(oProtoCsmp, oTvbData(), 'CSMP TLV Data')
   local uiIndex = 0

   -- Loop through data and add the TLVs
   while( uiIndex < oTvbData:len()-2 ) do
      local typeLen, typeValue = getVarInt( oTvbData(uiIndex) ) -- Get TLV ID
      local lengthLen, lengthValue = getVarInt( oTvbData(uiIndex+typeLen) ) -- Get TLV Length
      local dataOffset = uiIndex + typeLen + lengthLen
      local dataBuf = oTvbData(dataOffset, lengthValue) -- Get TLV Data

      -- Add the TLV subtree
      local oTlvTree = oSubtree:add(oProtoCsmp, oTvbData(uiIndex, typeLen + lengthLen + lengthValue), 
         string.format("TLV: %d %s", typeValue, tTlvIdStr[typeValue] or "TLV: Unknown"))

      oTlvTree:add(pfTlvId, oTvbData(uiIndex, typeLen), typeValue)
      oTlvTree:add(pfTlvLength, oTvbData(uiIndex + typeLen, lengthLen), lengthValue)
      oTlvTree:add(pfTlvData, dataBuf)

      -- Attempt to decode with ProtoBuf
      if protobufMessageMap[typeValue] then
         oPinfo.private["pb_msg_type"] = "message," .. protobufMessageMap[typeValue]
         oProtoProtobuf:call(dataBuf:tvb(), oPinfo, oTlvTree)
      end

      uiIndex = dataOffset + lengthValue
   end
end

-- Add dissector to CoAP Data Media Type Dissector Table
DissectorTable.get("media_type"):add("application/octet-stream", oProtoCsmp)

